from pydantic import BaseModel, Field
import datetime


# Pydantic model for Jobs
class JobTask(BaseModel):
    job_id: int = Field(..., description = "ID of the Job Task, defined by the system-user (not autogenerated by MongoDB)")
    work_order_id: int = Field(..., description = "Reference to the ID work_order, from the work_orders collection")
    factory: dict = Field(default={}, description="JSON document that includes the factory data such as factory_id, production_lines, production_lines.production_line_id, production_lines.machines")
    target_output: int = Field(..., description = "Quantity of items generated on the work order")
    nok_products: int = Field(default=0, description = "Quantity of no ok products from the work order, received by the simulator")
    quality_rate: int = Field(default=0, description = "Defined by the simulator, once the job is completed")