env:
  NODE_ENV: production
  INTERNAL_API_URL: http://leafy-factory-backend-web-app:80
  INTERNAL_WS_URL: ws://leafy-factory-backend-web-app:80
  NEXT_PUBLIC_BACKEND_URL: http://leafy-factory-backend-web-app:80

envSecrets:
  MONGO_URI: factory-mongodb-prod
  SQL_USERNAME: factory-mongodb-prod
  SQL_PASSWORD: factory-mongodb-prod
  SQL_HOSTNAME: factory-mongodb-prod
  SQL_DATABASE: factory-mongodb-prod

# serviceAccount:
#   enabled: true
#   name: irsa-prod