services:
  mqtt-broker:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: mqtt-broker
    environment:
      - MQTT_LISTENER_PORT=1883
    ports:
      - "1883:1883"
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
    command: /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf
    networks:
      - mqtt-network

networks:
  mqtt-network:
    driver: bridge