from pydantic import BaseModel, Field
import datetime

# Pydantic model for work orders
class WorkOrder(BaseModel):
    work_id: int = Field(..., description = "ID of the work order, defined by the system (not autogenerated by MongoDB)")
    planned_start_date: datetime.datetime = Field(..., description = "Planned start date for the work order")
    planned_end_date: datetime.datetime = Field(..., description = "Planned end date for the work order")
    actual_start: datetime.datetime = Field(..., description = "Date when actually the work order started")
    actual_end: datetime.datetime = Field(..., description = "Date when actually the work order ended")
    materials_used: dict = Field(default={}, description="Additional JSON data for the materials used")
    planned_cost: dict = Field(default={}, description="Additional JSON data for the planned cost")
    actual_cost: dict = Field(default={}, description="Additional JSON data for the additional cost")